version: '2'
services:

  app:
    build: .
    image: posobota/hello-world

  dev:
    image: posobota/hello-world
    volumes:
      - ./:/code
    command: /bin/bash

  xdebug:
    image: posobota/hello-world-xdebug
    build:
      context: .
      dockerfile: docker/xdebug/Dockerfile
    volumes:
      - ./:/code
